export enum SecurityEventType {
  TAB_SWITCH = 'TAB_SWITCH',
  FULLSCREEN_EXIT = 'FULLSCREEN_EXIT',
  COPY_PASTE = 'COPY_PASTE',
  DEVTOOLS_OPEN = 'DEVTOOLS_OPEN',
  MULTIPLE_FACE_DETECTED = 'MULTIPLE_FACE_DETECTED',
  IP_MISMATCH = 'IP_MISMATCH',
  USER_AGENT_MISMATCH = 'USER_AGENT_MISMATCH',
  AUTO_SUBMIT = 'AUTO_SUBMIT'
}
